### ISSUE TITLE
Fails to Load/Open on 4.26.2

### ISSUE THREAD

**Issue by Subressor** [UE4-OceanProject/Environment-Project#11]
![image](https://user-images.githubusercontent.com/40392247/117971185-73060880-b321-11eb-8237-b01308311d6d.png)

Steps to reproduce:
Download Master Branch to new folder
Right click uproject, swap engine version (4.26.2)
Double click uproject, allow to rebuild
Errors upon opening

**Comment by NightMare489** [comment]
I am using 4.26.2 and it is working fine for me.
you can try the following solutions and see if it works
1-Don't put the project in the root folder of C drive (put it in documents folder or another drive)
2-Make sure that no folder contains a space in its name (in your pic the folder "Temp Folder" contains a space)
3-Make the file path to your project shorter (I don't think it is the case here)
4-Make sure that all plugins are enabled in the project
